// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: ip.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createIP = `-- name: CreateIP :one
INSERT INTO ip_address (project_id, ip)
VALUES ((SELECT p.id FROM projects p WHERE p.project_name = $1), $2)
RETURNING id, project_id, ip, active
`

type CreateIPParams struct {
	ProjectName string `json:"project_name"`
	Ip          string `json:"ip"`
}

func (q *Queries) CreateIP(ctx context.Context, arg CreateIPParams) (IpAddress, error) {
	row := q.db.QueryRowContext(ctx, createIP, arg.ProjectName, arg.Ip)
	var i IpAddress
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Ip,
		&i.Active,
	)
	return i, err
}

const deleteIP = `-- name: DeleteIP :exec
DELETE
FROM ip_address
WHERE ip = $1
`

func (q *Queries) DeleteIP(ctx context.Context, ip string) error {
	_, err := q.db.ExecContext(ctx, deleteIP, ip)
	return err
}

const getAllIPs = `-- name: GetAllIPs :many
SELECT i.id, p.project_name, i.ip
FROM ip_address i
         INNER JOIN projects p on p.id = i.project_id
`

type GetAllIPsRow struct {
	ID          uuid.UUID `json:"id"`
	ProjectName string    `json:"project_name"`
	Ip          string    `json:"ip"`
}

func (q *Queries) GetAllIPs(ctx context.Context) ([]GetAllIPsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllIPs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllIPsRow
	for rows.Next() {
		var i GetAllIPsRow
		if err := rows.Scan(&i.ID, &i.ProjectName, &i.Ip); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIPsByProjectName = `-- name: GetIPsByProjectName :many
SELECT id, project_id, ip, active
FROM ip_address
WHERE project_id = (SELECT p.id FROM projects p WHERE p.project_name = $1)
`

func (q *Queries) GetIPsByProjectName(ctx context.Context, projectName string) ([]IpAddress, error) {
	rows, err := q.db.QueryContext(ctx, getIPsByProjectName, projectName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IpAddress
	for rows.Next() {
		var i IpAddress
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Ip,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const iPExists = `-- name: IPExists :one
SELECT EXISTS(SELECT 1 from ip_address where ip = $1)
`

func (q *Queries) IPExists(ctx context.Context, ip string) (bool, error) {
	row := q.db.QueryRowContext(ctx, iPExists, ip)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateIP = `-- name: UpdateIP :exec
UPDATE ip_address
SET ip = $2
WHERE id = (SELECT i.id FROM ip_address i WHERE i.ip = $1)
`

type UpdateIPParams struct {
	Ip   string `json:"ip"`
	Ip_2 string `json:"ip_2"`
}

func (q *Queries) UpdateIP(ctx context.Context, arg UpdateIPParams) error {
	_, err := q.db.ExecContext(ctx, updateIP, arg.Ip, arg.Ip_2)
	return err
}
