// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: ip.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createIP = `-- name: CreateIP :one
INSERT INTO ip_address (project_id, ip)
VALUES ((SELECT p.id FROM projects p WHERE p.project_name = $1), $2)
RETURNING id, project_id, ip
`

type CreateIPParams struct {
	ProjectName string `json:"project_name"`
	Ip          string `json:"ip"`
}

func (q *Queries) CreateIP(ctx context.Context, arg CreateIPParams) (IpAddress, error) {
	row := q.db.QueryRowContext(ctx, createIP, arg.ProjectName, arg.Ip)
	var i IpAddress
	err := row.Scan(&i.ID, &i.ProjectID, &i.Ip)
	return i, err
}

const getAllIPs = `-- name: GetAllIPs :many
SELECT id, project_id, ip
FROM ip_address
`

func (q *Queries) GetAllIPs(ctx context.Context) ([]IpAddress, error) {
	rows, err := q.db.QueryContext(ctx, getAllIPs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IpAddress
	for rows.Next() {
		var i IpAddress
		if err := rows.Scan(&i.ID, &i.ProjectID, &i.Ip); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIPs = `-- name: GetIPs :many
SELECT id, project_id, ip
FROM ip_address
WHERE project_id = $1
`

func (q *Queries) GetIPs(ctx context.Context, projectID uuid.UUID) ([]IpAddress, error) {
	rows, err := q.db.QueryContext(ctx, getIPs, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IpAddress
	for rows.Next() {
		var i IpAddress
		if err := rows.Scan(&i.ID, &i.ProjectID, &i.Ip); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const iPExists = `-- name: IPExists :one
SELECT EXISTS(SELECT 1 from ip_address where ip = $1)
`

func (q *Queries) IPExists(ctx context.Context, ip string) (bool, error) {
	row := q.db.QueryRowContext(ctx, iPExists, ip)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateIP = `-- name: UpdateIP :exec
UPDATE ip_address
SET ip = $2
WHERE id = (SELECT i.id FROM ip_address i WHERE i.ip = $1)
`

type UpdateIPParams struct {
	Ip   string `json:"ip"`
	Ip_2 string `json:"ip_2"`
}

func (q *Queries) UpdateIP(ctx context.Context, arg UpdateIPParams) error {
	_, err := q.db.ExecContext(ctx, updateIP, arg.Ip, arg.Ip_2)
	return err
}
