// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type IpAddress struct {
	ID          uuid.UUID
	ProjectName string
	Ip          string
}

type Project struct {
	ProjectName string
	Active      sql.NullBool
}

type Service struct {
	ID          uuid.UUID
	ProjectName string
	ServiceName string
	Url         string
}
