// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type IpAddress struct {
	ID        uuid.UUID    `json:"id"`
	ProjectID uuid.UUID    `json:"project_id"`
	Ip        string       `json:"ip"`
	Active    sql.NullBool `json:"active"`
}

type Project struct {
	ID          uuid.UUID    `json:"id"`
	ProjectName string       `json:"project_name"`
	Active      sql.NullBool `json:"active"`
}

type Service struct {
	ID          uuid.UUID    `json:"id"`
	ProjectID   uuid.UUID    `json:"project_id"`
	ServiceName string       `json:"service_name"`
	Url         string       `json:"url"`
	Active      sql.NullBool `json:"active"`
}
