// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: projects.sql

package database

import (
	"context"
	"database/sql"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (project_name, active)
VALUES ($1, $2)
RETURNING id, project_name, active
`

type CreateProjectParams struct {
	ProjectName string       `json:"project_name"`
	Active      sql.NullBool `json:"active"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.ProjectName, arg.Active)
	var i Project
	err := row.Scan(&i.ID, &i.ProjectName, &i.Active)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE
FROM projects
WHERE project_name = $1
`

func (q *Queries) DeleteProject(ctx context.Context, projectName string) error {
	_, err := q.db.ExecContext(ctx, deleteProject, projectName)
	return err
}

const getProjectByName = `-- name: GetProjectByName :many
SELECT id, project_name, active
FROM projects p
WHERE project_name = $1
`

func (q *Queries) GetProjectByName(ctx context.Context, projectName string) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, getProjectByName, projectName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(&i.ID, &i.ProjectName, &i.Active); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjects = `-- name: GetProjects :many
SELECT id, project_name, active
FROM projects
ORDER BY project_name
`

func (q *Queries) GetProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, getProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(&i.ID, &i.ProjectName, &i.Active); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectExists = `-- name: ProjectExists :one
SELECT EXISTS(SELECT 1 FROM projects p WHERE p.project_name = $1)
`

func (q *Queries) ProjectExists(ctx context.Context, projectName string) (bool, error) {
	row := q.db.QueryRowContext(ctx, projectExists, projectName)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const projectSetState = `-- name: ProjectSetState :exec
UPDATE projects
SET active = $2
WHERE project_name = $1
`

type ProjectSetStateParams struct {
	ProjectName string       `json:"project_name"`
	Active      sql.NullBool `json:"active"`
}

func (q *Queries) ProjectSetState(ctx context.Context, arg ProjectSetStateParams) error {
	_, err := q.db.ExecContext(ctx, projectSetState, arg.ProjectName, arg.Active)
	return err
}

const updateProject = `-- name: UpdateProject :exec
UPDATE projects
SET project_name = $2,
    active       = $3
WHERE id = (SELECT id FROM projects p WHERE p.project_name = $1)
`

type UpdateProjectParams struct {
	ProjectName   string       `json:"project_name"`
	ProjectName_2 string       `json:"project_name_2"`
	Active        sql.NullBool `json:"active"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) error {
	_, err := q.db.ExecContext(ctx, updateProject, arg.ProjectName, arg.ProjectName_2, arg.Active)
	return err
}
