// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: query.sql

package database

import (
	"context"
	"database/sql"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (project_name, active)
VALUES ($1, $2)
RETURNING project_name, active
`

type CreateProjectParams struct {
	ProjectName string
	Active      sql.NullBool
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.ProjectName, arg.Active)
	var i Project
	err := row.Scan(&i.ProjectName, &i.Active)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE
FROM projects
WHERE project_name = $1
`

func (q *Queries) DeleteProject(ctx context.Context, projectName string) error {
	_, err := q.db.ExecContext(ctx, deleteProject, projectName)
	return err
}

const getProject = `-- name: GetProject :one
SELECT project_name, active
FROM projects
WHERE project_name = $1
LIMIT 1
`

func (q *Queries) GetProject(ctx context.Context, projectName string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, projectName)
	var i Project
	err := row.Scan(&i.ProjectName, &i.Active)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT project_name, active
FROM projects
ORDER BY project_name
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(&i.ProjectName, &i.Active); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectSetActive = `-- name: ProjectSetActive :exec
UPDATE projects
SET active = $2
WHERE project_name = $1
`

type ProjectSetActiveParams struct {
	ProjectName string
	Active      sql.NullBool
}

func (q *Queries) ProjectSetActive(ctx context.Context, arg ProjectSetActiveParams) error {
	_, err := q.db.ExecContext(ctx, projectSetActive, arg.ProjectName, arg.Active)
	return err
}

const updateProject = `-- name: UpdateProject :exec
UPDATE projects
SET project_name = $2,
    active       = $3
WHERE project_name = $1
`

type UpdateProjectParams struct {
	ProjectName   string
	ProjectName_2 string
	Active        sql.NullBool
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) error {
	_, err := q.db.ExecContext(ctx, updateProject, arg.ProjectName, arg.ProjectName_2, arg.Active)
	return err
}
