// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: services.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createService = `-- name: CreateService :exec
INSERT INTO services (project_id, service_name, url)
VALUES ($1, $2, $3)
RETURNING id, project_id, service_name, url
`

type CreateServiceParams struct {
	ProjectID   uuid.UUID
	ServiceName string
	Url         string
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) error {
	_, err := q.db.ExecContext(ctx, createService, arg.ProjectID, arg.ServiceName, arg.Url)
	return err
}

const deleteService = `-- name: DeleteService :exec
DELETE
FROM services
WHERE project_id = $1
  AND service_name = $2
`

type DeleteServiceParams struct {
	ProjectID   uuid.UUID
	ServiceName string
}

func (q *Queries) DeleteService(ctx context.Context, arg DeleteServiceParams) error {
	_, err := q.db.ExecContext(ctx, deleteService, arg.ProjectID, arg.ServiceName)
	return err
}

const getService = `-- name: GetService :one
SELECT id, project_id, service_name, url
FROM services
WHERE project_id = $1
  AND service_name = $2
LIMIT 1
`

type GetServiceParams struct {
	ProjectID   uuid.UUID
	ServiceName string
}

func (q *Queries) GetService(ctx context.Context, arg GetServiceParams) (Service, error) {
	row := q.db.QueryRowContext(ctx, getService, arg.ProjectID, arg.ServiceName)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ServiceName,
		&i.Url,
	)
	return i, err
}

const getServices = `-- name: GetServices :many
SELECT id, project_id, service_name, url
FROM services
WHERE project_id = $1
`

func (q *Queries) GetServices(ctx context.Context, projectID uuid.UUID) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, getServices, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ServiceName,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateService = `-- name: UpdateService :exec
UPDATE services
SET service_name = $2,
    url          = $3
WHERE project_id = $1
`

type UpdateServiceParams struct {
	ProjectID   uuid.UUID
	ServiceName string
	Url         string
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) error {
	_, err := q.db.ExecContext(ctx, updateService, arg.ProjectID, arg.ServiceName, arg.Url)
	return err
}
